package us.ilite.common.types.drive;

import com.flybotix.hfr.codex.CodexOf;

public enum EDriveData implements CodexOf<Double> {

    // Sensor inputs
    L_ACTUAL_POS_FT, R_ACTUAL_POS_FT,
    L_DESIRED_POS_FT, R_DESIRED_POS_FT,
    L_ACTUAL_VEL_FT_s, R_ACTUAL_VEL_FT_s,
    L_ACTUAL_POS_meters, R_ACTUAL_POS_meters,
    L_DESIRED_POS_meters, R_DESIRED_POS_meters,
    L_ACTUAL_VEL_meters_s, R_ACTUAL_VEL_meters_s,
    L_ACTUAL_VEL_RPM, R_ACTUAL_VEL_RPM,
    L_DESIRED_VEL_RPM, R_DESIRED_VEL_RPM,
    LEFT_CURRENT, RIGHT_CURRENT,
    LEFT_VOLTAGE, RIGHT_VOLTAGE,
    DESIRED_LEFT_VOLTAGE, DESIRED_RIGHT_VOLTAGE,
    DESIRED_LEFT_ft_s, DESIRED_RIGHT_ft_s,
    DESIRED_LEFT_m_s, DESIRED_RIGHT_m_s,
    IS_CURRENT_LIMITING,

    DESIRED_TURN_ANGLE_deg,
    ACTUAL_TURN_ANGLE_deg,
    GREYHILL_ACTUAL_RIGHT_ft, GREYHILL_ACTUAL_LEFT_ft,
    GREYHILL_ACTUAL_RIGHT_meters, GREYHILL_ACTUAL_LEFT_meters,


    DESIRED_TURN_PCT, DESIRED_THROTTLE_PCT,
    GET_X_OFFSET, GET_Y_OFFSET,
    GET_X_OFFSET_METERS, GET_Y_OFFSET_METERS,
    DESIRED_LEFT_PCT, DESIRED_RIGHT_PCT,
    ACTUAL_LEFT_PCT, ACTUAL_RIGHT_PCT,

    DELTA_HEADING,
    ACTUAL_HEADING_RADIANS,
    SET_YAW_RATE_deg_s,
    GYRO_RATE,

    NEUTRAL_MODE,
    STATE,
    L_DESIRED_DRIVE_FT_SEC,
    R_DESIRED_DRIVE_FT_SEC
    ;

}
