package us.ilite.common.types;

public enum EHangerModuleData {

    DESIRED_HANGER_POSITION1,
    DESIRED_HANGER_POSITION2,

    CURRENT_HANGER_POSITION1,
    CURRENT_HANGER_POSITION2,

    CURRENT_ENCODER_TICKS,
    DESDIRED_ENCODER_TICKS;



    }
