package us.ilite.common.types;

import com.flybotix.hfr.codex.CodexOf;

public enum EPowerCellData implements CodexOf<Double> {
    UNUSED,
    ENTRY_BEAM,
    SECONDARY_BREAM,
    EXIT_BEAM,

    // etc - 1 per beam break sensor

    DESIRED_H_VELOCITY,
    DESIRED_V_VELOCITY,

    CURRENT_ARM_ANGLE,
    DESIRED_ARM_ANGLE,

    CURRENT_INTAKE_VELOCITY_FT_S,
    DESIRED_INTAKE_VELOCITY_FT_S,

    CURRENT_INDEXING_STATE,

    CURRENT_AMOUNT_OF_SENSORS_BROKEN,
    DESIRED_AMOUNT_OF_SENSORS_BROKEN,

    ALL_BEAMS_BROKEN,

    INTAKE_PIVOT_CURRENT,
    INTAKE_ROLLER_CURRENT,
    SERIALIZER_CURRENT,
    VERTICAL_CURRENT
}
