package us.ilite.common.types;

public enum EShooterSystemData {
    CURRENT_FLYWHEEL_VELOCITY,
    TARGET_FLYWHEEL_VELOCITY,
    DESIRED_FLYWHEEL_VELOCITY,
    CURRENT_LIMELIGHT_TARGET,
    TARGET_LIMELIGHT_TARGET,
    CURRENT_TURRET_VELOCITY,
    TARGET_TURRET_VELOCITY,
    CURRENT_HOOD_ANGLE,
    TARGET_HOOD_ANGLE,
    CURRENT_ACCELERATOR_VELOCITY,
    TARGET_ACCELERATOR_VELOCITY,
    CURRENT_TURRET_MODE,
    TARGET_TURRET_MODE
}
