package us.ilite.common.types;

public enum EShooterSystemData {
    CURRENT_FLYWHEEL_VELOCITY,
    TARGET_FLYWHEEL_VELOCITY,

    CURRENT_FEEDER_VELOCITY,
    TARGET_FEEDER_VELOCITY,

    CURRENT_TURRET_VELOCITY,
    TARGET_TURRET_VELOCITY,
    ;

}
