package us.ilite.common.types;

public enum EShooterSystemData {
    CURRENT_FLYWHEEL_VELOCITY,
    TARGET_FLYWHEEL_VELOCITY,

    FLYWHEEL_IS_MAX_VELOCITY,
    FLYWHEEL_DISTANCE_BASED_SPEED,

    CURRENT_FEEDER_VELOCITY,
    TARGET_FEEDER_VELOCITY,

    CURRENT_TURRET_VELOCITY,
    TARGET_TURRET_VELOCITY,

    CURRENT_SERVO_ANGLE,
    TARGET_SERVO_ANGLE,

    SERVO_DISTANCE_BASED_ANGLE,
    SERVO_POTENTIOMETER_BASED_ANGLE,

    CURRENT_POTENTIOMETER_TURNS,
    TARGET_POTENTIOMETER_TURNS
}
